### ISSUE TITLE
what's the license?

### ISSUE THREAD

**Issue by pieper** [syhlalala/PAM-AE#1]
Hi - this looks cool.  👍 

What's the license?  Maybe MIT or Apache license would be good to promote use in a wide range of applications and build up a community.

**Comment by syhlalala** [comment]
Hi, thanks for your interest!

I just added the copyright file in the repository. Also as mentioned, you can find a more recent version of this library here: https://github.com/cmuparlay/PAM

We are also working on more related applications, and if you know of any of interest, it would be helpful :)

**Comment by pieper** [comment]
Great - thanks for adding the copyright file. 👍   And thanks for choosing to make this available for people to use 👍 👍 

(sorry for filing this issue here - i noticed the link to the new repository just after I filed this issue).
